### ISSUE TITLE
Error running ChromeREPL

### ISSUE THREAD

**Issue by BHerbulot** [acarabott/ChromeConsole#2]
Hi, i  installed ChromeREPL plugin from package control but this one doesn't work. Here the errors i have in my console:

```python

reloading plugin Chrome REPL.ChromeREPL
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/bhe/Library/Application Support/Sublime Text 3/Installed Packages/Chrome REPL.sublime-package/ChromeREPL.py", line 5, in <module>
ImportError: No module named 'ChromeREPL'
reloading plugin Chrome REPL.ChromeREPLConnection
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/bhe/Library/Application Support/Sublime Text 3/Installed Packages/Chrome REPL.sublime-package/ChromeREPLConnection.py", line 4, in <module>
ImportError: No module named 'ChromeREPL'
```
Did you have any idea how to resolve it? Thanks

**Comment by acarabott** [comment]
Ah, this will require a fix in package control, but for now rename the package to ChromeREPL.sublime-package

**Comment by BHerbulot** [comment]
Thank but this doesn't work because it get its original name back each time. I think its sublime with this `reload_plugin` method wich undo the file name. By the way i installed it manually and is work. Thank .

**Comment by acarabott** [comment]
Great. I’ve put in a pull request to get it changed.

Let me know if any other issues if you find them!
